<?php

/**
 * @file
 * Contains hcbeerfest_core.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hcbeerfest_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hcbeerfest_core module.
    case 'help.page.hcbeerfest_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module for the HCBF') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme();
 */
function hcbeerfest_core_theme() {
  return array(
    'hcbeerfest_music' => array(
      'template' => 'hcbeerfest_music',
      'variables' => array('bands' => NULL),
    ),
    'hcbeerfest_breweries' => array(
      'template' => 'hcbeerfest_breweries',
      'variables' => array('breweries' => NULL),
    ),
    'hcbeerfest_about' => array(
      'template' => 'hcbeerfest_about',
      'variables' => array(),
    ),
    'hcbeerfest_sponsors' => array(
      'template' => 'hcbeerfest_sponsors',
      'variables' => array(),
    ),
    'hcbeerfest_food' => array(
      'template' => 'hcbeerfest_food',
      'variables' => array(),
    ),
    'hcbeerfest_seminars' => array(
      'template' => 'hcbeerfest_seminars',
      'variables' => array(),
    ),
  );
}
